name: Build and Deploy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run Unit Tests
        run: ./gradlew test

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease --warning-mode all

      - name: Make gradlew executable
        run: chmod +x ./gradlew

