name: Build and Deploy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Build APK
      - name: Build APK
        run: ./gradlew assembleRelease --warning-mode all

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: weather-challenge-apk
          path: app/build/outputs/apk/debug/app-debug.apk